import * as XLSX from 'xlsx';

class ReportsExportService {
  
  // Export analytics data to Excel
  static async exportToExcel(exportData, filename) {
    try {
      const workbook = XLSX.utils.book_new();
      
      if (exportData.type === 'clients') {
        this.addClientSheetsToWorkbook(workbook, exportData.data);
      }
      
      // Add metadata sheet
      this.addMetadataSheet(workbook, exportData);
      
      // Write and download the file
      XLSX.writeFile(workbook, `${filename}.xlsx`);
      
    } catch (error) {
      console.error('Error exporting to Excel:', error);
      throw new Error('Failed to export data to Excel');
    }
  }
  
  // Export analytics data to CSV
  static async exportToCSV(exportData, filename) {
    try {
      let csvContent = '';
      
      if (exportData.type === 'clients') {
        csvContent = this.generateClientCSV(exportData.data);
      }
      
      // Download CSV file
      this.downloadCSV(csvContent, `${filename}.csv`);
      
    } catch (error) {
      console.error('Error exporting to CSV:', error);
      throw new Error('Failed to export data to CSV');
    }
  }
  
  // Add client-specific sheets to workbook
  static addClientSheetsToWorkbook(workbook, data) {
    // Timeline data sheet
    if (data.timeline && data.timeline.length > 0) {
      const timelineData = data.timeline.map(item => ({
        'Year': new Date(item.date).getFullYear(),
        'New Clients': item.clients,
        'Date': item.date.toISOString().split('T')[0]
      }));
      
      const timelineSheet = XLSX.utils.json_to_sheet(timelineData);
      XLSX.utils.book_append_sheet(workbook, timelineSheet, 'Client Timeline');
    }
    
    // Type distribution sheet
    if (data.typeDistribution && data.typeDistribution.length > 0) {
      const typeData = data.typeDistribution.map(item => ({
        'Client Type': item.name,
        'Count': item.count,
        'Percentage': ((item.count / data.totalClients) * 100).toFixed(2) + '%'
      }));
      
      const typeSheet = XLSX.utils.json_to_sheet(typeData);
      XLSX.utils.book_append_sheet(workbook, typeSheet, 'Type Distribution');
    }
    
    // Summary sheet
    const summaryData = [
      { 'Metric': 'Total Clients', 'Value': data.totalClients || 0 },
      { 'Metric': 'Active Clients', 'Value': data.activeClients || 0 },
      { 'Metric': 'New Clients This Month', 'Value': data.newClientsThisMonth || 0 },
      { 'Metric': 'Growth Rate', 'Value': data.growthRate || '0%' },
      { 'Metric': 'Most Common Type', 'Value': data.mostCommonType || 'N/A' }
    ];
    
    const summarySheet = XLSX.utils.json_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');
  }
  
  // Add metadata sheet to workbook
  static addMetadataSheet(workbook, exportData) {
    const metadataData = [
      { 'Property': 'Export Type', 'Value': 'Client Analytics' },
      { 'Property': 'Export Date', 'Value': new Date().toISOString().split('T')[0] },
      { 'Property': 'Export Time', 'Value': new Date().toLocaleTimeString() },
      { 'Property': 'Filters Applied', 'Value': JSON.stringify(exportData.filters) },
      { 'Property': 'Generated By', 'Value': 'CRM Dashboard System' }
    ];
    
    const metadataSheet = XLSX.utils.json_to_sheet(metadataData);
    XLSX.utils.book_append_sheet(workbook, metadataSheet, 'Export Info');
  }
  
  // Generate CSV content for client data
  static generateClientCSV(data) {
    let csv = 'Client Analytics Export\n\n';
    
    // Summary section
    csv += 'SUMMARY\n';
    csv += 'Metric,Value\n';
    csv += `Total Clients,${data.totalClients || 0}\n`;
    csv += `Active Clients,${data.activeClients || 0}\n`;
    csv += `New Clients This Month,${data.newClientsThisMonth || 0}\n`;
    csv += `Growth Rate,${data.growthRate || '0%'}\n`;
    csv += `Most Common Type,${data.mostCommonType || 'N/A'}\n\n`;
    
    // Timeline section
    if (data.timeline && data.timeline.length > 0) {
      csv += 'CLIENT TIMELINE\n';
      csv += 'Year,New Clients,Date\n';
      data.timeline.forEach(item => {
        csv += `${new Date(item.date).getFullYear()},${item.clients},${item.date.toISOString().split('T')[0]}\n`;
      });
      csv += '\n';
    }
    
    // Type distribution section
    if (data.typeDistribution && data.typeDistribution.length > 0) {
      csv += 'TYPE DISTRIBUTION\n';
      csv += 'Client Type,Count,Percentage\n';
      data.typeDistribution.forEach(item => {
        const percentage = ((item.count / data.totalClients) * 100).toFixed(2);
        csv += `${item.name},${item.count},${percentage}%\n`;
      });
    }
    
    return csv;
  }
  
  // Download CSV file
  static downloadCSV(csvContent, filename) {
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    
    if (link.download !== undefined) {
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', filename);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  }
}

export default ReportsExportService;